export const darkTheme = {
  colors: {
    primary: {
      main: "#141414",
      light: "#2B303B",
      dark: "#262626",
      text: "#D3D3D3",
    },
    secondary: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    error: {
      main: "#FF0000",
      light: "",
      dark: "",
      text: "",
    },
    warning: {
      main: "#FFA500",
      light: "",
      dark: "",
      text: "",
    },
    info: {
      main: "#00FFFF",
      light: "",
      dark: "",
      text: "",
    },
    success: {
      main: "#00FF00",
      light: "",
      dark: "",
      text: "",
    },
    common: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    text: {
      primary: "",
      secondary: "",
      disabled: "",
    },
    background: "#141414",
    action: {
      background: "#6FB1D8",
      color: "#040B11",
      activeText: "",
      activeBackground: "",
      activeOpacity: "",
      hoverText: "",
      hoverBackground: "",
      hoverOpacity: "",
      selectedText: "",
      selectedBackground: "",
      selectedOpacity: "",
      disabledText: "",
      disabledBackground: "",
      disabledOpacity: "",
      focusText: "",
      focusBackground: "",
      focusOpacity: "",
    },
  },
  typography: {
    general: {
      fontFamily: "'Chakra Petch', sans-serif",
      color: "#D3D3D3",
    },
    h1: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 64,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h2: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 56,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h3: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 48,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h4: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 40,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h5: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 32,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h6: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 24,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body1: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body2: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body3: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body4: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body5: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body6: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    button: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    caption: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    link: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
  },
  spacing: {
    padding: {
      none: 0,
      small: 8,
      medium: 16,
      large: 24,
      xlarge: 32,
    },
    margin: {
      none: 0,
      small: 8,
      medium: 16,
      large: 24,
      xlarge: 32,
    },
  },
  border: {
    radius: {
      sharp: 0,
      small: 4,
      medium: 8,
      large: 16,
    },
  },
  flex: {
    gap: {
      none: 0,
      small: 4,
      medium: 8,
      large: 16,
    },
  },
  transition: {
    delay: {
      none: "",
      short: "",
      medium: "",
      long: "",
    },
    duration: {
      short: "",
      medium: "",
      long: "",
    },
    property: "",
    easing: {
      easeIn: "",
      easeOut: "",
      easeInOut: "",
      sharp: "",
    },
  },
  breakpoints: {
    xl: 1400,
    lg: 992,
    md: 768,
    sm: 576,
  },
  components: {},
};
