export const lightTheme = {
  colors: {
    primary: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    secondary: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    error: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    warning: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    info: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    success: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    common: {
      main: "",
      light: "",
      dark: "",
      text: "",
    },
    text: {
      primary: "",
      secondary: "",
      disabled: "",
    },
    background: "#95DBD9",
    action: {
      background: "#2A7976",
      color: "#FFFFFF",
      activeText: "",
      activeBackground: "",
      activeOpacity: "",
      hoverText: "",
      hoverBackground: "",
      hoverOpacity: "",
      selectedText: "",
      selectedBackground: "",
      selectedOpacity: "",
      disabledText: "",
      disabledBackground: "",
      disabledOpacity: "",
      focusText: "",
      focusBackground: "",
      focusOpacity: "",
    },
  },
  typography: {
    general: {
      fontFamily: "'Chakra Petch', sans-serif",
      color: "#040B11",
    },
    h1: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 64,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h2: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 56,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h3: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 48,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h4: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 40,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h5: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 32,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    h6: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: 24,
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body1: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body2: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body3: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body4: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body5: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    body6: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    button: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    caption: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
    link: {
      fontFamily: "'Chakra Petch', sans-serif",
      fontSize: "",
      fontWeight: 400,
      fontStyle: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      color: "",
    },
  },
  spacing: {
    padding: {
      none: "",
      small: "",
      medium: "",
      large: "",
      xlarge: "",
    },
    margin: {
      none: "",
      small: "",
      medium: "",
      large: "",
      xlarge: "",
    },
  },
  transition: {
    delay: {
      none: "",
      short: "",
      medium: "",
      long: "",
    },
    duration: {
      short: "",
      medium: "",
      long: "",
    },
    property: "",
    easing: {
      easeIn: "",
      easeOut: "",
      easeInOut: "",
      sharp: "",
    },
  },
  breakpoints: {
    xl: 1400,
    lg: 992,
    md: 768,
    sm: 576,
  },
  components: {},
};
